// Shared mapping of SportAPI (Sofascore) team name variants to our 3-letter IDs.
// Used by both the sync route and the live route.
export const NAME_TO_ID: Record<string, string> = {
  "Argentina": "ARG",
  "Spain": "ESP",
  "France": "FRA",
  "England": "ENG",
  "Portugal": "POR",
  "Brazil": "BRA",
  "Morocco": "MAR",
  "Netherlands": "NED",
  "Belgium": "BEL",
  "Germany": "GER",
  "Croatia": "CRO",
  "Colombia": "COL",
  "Mexico": "MEX",
  "Senegal": "SEN",
  "Uruguay": "URU",
  "United States": "USA", "USA": "USA",
  "Japan": "JPN",
  "Switzerland": "SUI",
  "Iran": "IRN", "IR Iran": "IRN",
  "Turkiye": "TUR", "Turkey": "TUR", "Türkiye": "TUR",
  "Ecuador": "ECU",
  "Austria": "AUT",
  "South Korea": "KOR", "Korea Republic": "KOR",
  "Australia": "AUS",
  "Algeria": "ALG",
  "Egypt": "EGY",
  "Canada": "CAN",
  "Norway": "NOR",
  "Ivory Coast": "CIV", "Cote d'Ivoire": "CIV", "Côte d'Ivoire": "CIV", "Côte D'Ivoire": "CIV",
  "Panama": "PAN",
  "Sweden": "SWE",
  "Czechia": "CZE", "Czech Republic": "CZE",
  "Paraguay": "PAR",
  "Scotland": "SCO",
  "Tunisia": "TUN",
  "DR Congo": "COD", "Congo DR": "COD", "Democratic Republic of Congo": "COD",
  "Uzbekistan": "UZB",
  "New Zealand": "NZL",
};
